language: python

python:
    - '3.7'

# whitelist
branches:
    only:
        - master

install:
    - pip install pycodestyle
    - pip install pytest
    - pip install coverage
    - pip install codecov
   
script:
    - pycodestyle cardinality.py test_cardinality.py 
    - coverage run -m pytest test_cardinality.py
    - coverage report -m cardinality.py

after_success:
    - codecov
